// src/pages/platform/ClaimsManagement.tsx

import React, { useState } from 'react';
import { PageHeader } from '@/components/ui/page-header';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Search, Filter, Eye, CheckCircle, XCircle, Clock, AlertTriangle } from 'lucide-react';

export const PlatformClaimsManagement: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [tenantFilter, setTenantFilter] = useState('all');
  const [selectedClaim, setSelectedClaim] = useState<any>(null);

  const claims = [
    {
      id: 'CLM-001',
      date: '2024-07-15',
      customer: 'Muhammad Ali',
      phone: '+92-300-1234567',
      tenant: 'PowerCell Industries',
      brand: 'Volta',
      product: 'VL120-45AH',
      serialNumber: 'VL120230001',
      purchaseDate: '2023-05-15',
      issue: 'Battery not holding charge',
      status: 'pending',
      priority: 'high',
      retailer: 'AutoMart Central'
    },
    {
      id: 'CLM-002',
      date: '2024-07-14',
      customer: 'Ayesha Khan',
      phone: '+92-301-2345678',
      tenant: 'EnergyMax Solutions',
      brand: 'Osaka',
      product: 'OS80-35AH',
      serialNumber: 'OS80230002',
      purchaseDate: '2023-08-20',
      issue: 'Physical damage to terminals',
      status: 'approved',
      priority: 'medium',
      retailer: 'Power Zone Lahore'
    },
    {
      id: 'CLM-003',
      date: '2024-07-13',
      customer: 'Ahmed Hassan',
      phone: '+92-302-3456789',
      tenant: 'BatteryTech Corp',
      brand: 'Fujika',
      product: 'FK65-28AH',
      serialNumber: 'FK65230003',
      purchaseDate: '2024-01-10',
      issue: 'Overheating during use',
      status: 'rejected',
      priority: 'low',
      retailer: 'Battery World'
    },
    {
      id: 'CLM-004',
      date: '2024-07-12',
      customer: 'Fatima Sheikh',
      phone: '+92-303-4567890',
      tenant: 'PowerCell Industries',
      brand: 'SAGA',
      product: 'SG100-40AH',
      serialNumber: 'SG100230004',
      purchaseDate: '2023-12-05',
      issue: 'Sudden power loss',
      status: 'processing',
      priority: 'high',
      retailer: 'Tech Solutions'
    }
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'pending': return 'default';
      case 'processing': return 'secondary';
      case 'approved': return 'default';
      case 'rejected': return 'destructive';
      default: return 'outline';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return 'destructive';
      case 'medium': return 'default';
      case 'low': return 'secondary';
      default: return 'outline';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'pending': return Clock;
      case 'processing': return AlertTriangle;
      case 'approved': return CheckCircle;
      case 'rejected': return XCircle;
      default: return Clock;
    }
  };

  const filteredClaims = claims.filter(claim => {
    const matchesSearch = claim.customer.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         claim.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         claim.product.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         claim.tenant.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'all' || claim.status === statusFilter;
    const matchesTenant = tenantFilter === 'all' || claim.tenant === tenantFilter;
    return matchesSearch && matchesStatus && matchesTenant;
  });

  return (
    <div className="space-y-6">
      <PageHeader
        title="Platform Claims Management" 
        description="Process and manage warranty claims across all tenant organizations"
      />
      
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Claims</CardTitle>
            <Clock className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{claims.length}</div>
            <p className="text-xs text-muted-foreground">+12 from last week</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Pending</CardTitle>
            <AlertTriangle className="h-4 w-4 text-warning" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {claims.filter(c => c.status === 'pending').length}
            </div>
            <p className="text-xs text-muted-foreground">Requires attention</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Approved</CardTitle>
            <CheckCircle className="h-4 w-4 text-success" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {claims.filter(c => c.status === 'approved').length}
            </div>
            <p className="text-xs text-muted-foreground">This month</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Rejected</CardTitle>
            <XCircle className="h-4 w-4 text-destructive" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {claims.filter(c => c.status === 'rejected').length}
            </div>
            <p className="text-xs text-muted-foreground">This month</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Platform Warranty Claims</CardTitle>
          <CardDescription>Review and process customer warranty claims across all tenants</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4 mb-6">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search claims..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-48">
                <Filter className="h-4 w-4 mr-2" />
                <SelectValue placeholder="Filter by status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                <SelectItem value="pending">Pending</SelectItem>
                <SelectItem value="processing">Processing</SelectItem>
                <SelectItem value="approved">Approved</SelectItem>
                <SelectItem value="rejected">Rejected</SelectItem>
              </SelectContent>
            </Select>
            <Select value={tenantFilter} onValueChange={setTenantFilter}>
              <SelectTrigger className="w-48">
                <Filter className="h-4 w-4 mr-2" />
                <SelectValue placeholder="Filter by tenant" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Tenants</SelectItem>
                <SelectItem value="PowerCell Industries">PowerCell Industries</SelectItem>
                <SelectItem value="EnergyMax Solutions">EnergyMax Solutions</SelectItem>
                <SelectItem value="BatteryTech Corp">BatteryTech Corp</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Claim ID</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Customer</TableHead>
                  <TableHead>Tenant</TableHead>
                  <TableHead>Product</TableHead>
                  <TableHead>Issue</TableHead>
                  <TableHead>Priority</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredClaims.map((claim) => {
                  const StatusIcon = getStatusIcon(claim.status);
                  return (
                    <TableRow key={claim.id}>
                      <TableCell className="font-medium">{claim.id}</TableCell>
                      <TableCell>{claim.date}</TableCell>
                      <TableCell>
                        <div>
                          <p className="font-medium">{claim.customer}</p>
                          <p className="text-xs text-muted-foreground">{claim.phone}</p>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div>
                          <p className="font-medium">{claim.tenant}</p>
                          <p className="text-xs text-muted-foreground">{claim.brand}</p>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div>
                          <p className="font-medium">{claim.product}</p>
                          <p className="text-xs text-muted-foreground font-mono">{claim.serialNumber}</p>
                        </div>
                      </TableCell>
                      <TableCell className="max-w-48 truncate">{claim.issue}</TableCell>
                      <TableCell>
                        <Badge variant={getPriorityColor(claim.priority)}>
                          {claim.priority}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <Badge variant={getStatusColor(claim.status)} className="flex items-center gap-1 w-fit">
                          <StatusIcon className="h-3 w-3" />
                          {claim.status}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <Dialog>
                          <DialogTrigger asChild>
                            <Button 
                              variant="outline" 
                              size="sm"
                              onClick={() => setSelectedClaim(claim)}
                            >
                              <Eye className="h-3 w-3 mr-1" />
                              Review
                            </Button>
                          </DialogTrigger>
                          <DialogContent className="sm:max-w-[600px]">
                            <DialogHeader>
                              <DialogTitle>Claim Details - {selectedClaim?.id}</DialogTitle>
                              <DialogDescription>
                                Review and process warranty claim
                              </DialogDescription>
                            </DialogHeader>
                            {selectedClaim && (
                              <div className="space-y-4">
                                <div className="grid grid-cols-2 gap-4">
                                  <div>
                                    <Label className="text-sm font-medium">Customer</Label>
                                    <p>{selectedClaim.customer}</p>
                                    <p className="text-sm text-muted-foreground">{selectedClaim.phone}</p>
                                  </div>
                                  <div>
                                    <Label className="text-sm font-medium">Tenant</Label>
                                    <p>{selectedClaim.tenant}</p>
                                    <p className="text-sm text-muted-foreground">{selectedClaim.brand}</p>
                                  </div>
                                  <div>
                                    <Label className="text-sm font-medium">Product</Label>
                                    <p>{selectedClaim.product}</p>
                                    <p className="text-sm text-muted-foreground font-mono">{selectedClaim.serialNumber}</p>
                                  </div>
                                  <div>
                                    <Label className="text-sm font-medium">Purchase Date</Label>
                                    <p>{selectedClaim.purchaseDate}</p>
                                  </div>
                                  <div>
                                    <Label className="text-sm font-medium">Retailer</Label>
                                    <p>{selectedClaim.retailer}</p>
                                  </div>
                                </div>
                                <div>
                                  <Label className="text-sm font-medium">Issue Description</Label>
                                  <p className="mt-1">{selectedClaim.issue}</p>
                                </div>
                                <div>
                                  <Label htmlFor="admin-notes">Platform Admin Notes</Label>
                                  <Textarea 
                                    id="admin-notes" 
                                    placeholder="Add platform-level notes about this claim..."
                                    className="mt-2"
                                  />
                                </div>
                                <div className="flex gap-2 pt-4">
                                  <Button variant="default">
                                    <CheckCircle className="h-4 w-4 mr-2" />
                                    Approve
                                  </Button>
                                  <Button variant="destructive">
                                    <XCircle className="h-4 w-4 mr-2" />
                                    Reject
                                  </Button>
                                  <Button variant="outline">
                                    <AlertTriangle className="h-4 w-4 mr-2" />
                                    Request More Info
                                  </Button>
                                </div>
                              </div>
                            )}
                          </DialogContent>
                        </Dialog>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

// src/app/pages/platform/claims-management/claims-management.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDialogModule } from '@angular/material/dialog';
import { MatChipsModule } from '@angular/material/chips';
import { PageHeaderComponent } from '../../../components/ui/page-header/page-header.component';
import { MetricCardComponent } from '../../../components/ui/metric-card/metric-card.component';

@Component({
  selector: 'app-platform-claims-management',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatTableModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatIconModule,
    MatDialogModule,
    MatChipsModule,
    PageHeaderComponent,
    MetricCardComponent
  ],
  template: `
    <div class="space-y-6">
      <app-page-header
        title="Platform Claims Management" 
        description="Process and manage warranty claims across all tenant organizations">
      </app-page-header>
      
      <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
        <app-metric-card
          *ngFor="let metric of claimsMetrics"
          [title]="metric.label"
          [value]="metric.value"
          [icon]="metric.icon"
          [change]="metric.change">
        </app-metric-card>
      </div>

      <mat-card>
        <mat-card-header>
          <mat-card-title>Platform Warranty Claims</mat-card-title>
          <mat-card-subtitle>Review and process customer warranty claims across all tenants</mat-card-subtitle>
        </mat-card-header>
        <mat-card-content>
          <div class="flex gap-4 mb-6">
            <mat-form-field appearance="outline" class="flex-1">
              <mat-label>Search</mat-label>
              <input matInput 
                     [(ngModel)]="searchTerm"
                     placeholder="Search claims...">
              <mat-icon matPrefix>search</mat-icon>
            </mat-form-field>
            
            <mat-form-field appearance="outline" class="w-48">
              <mat-label>Status</mat-label>
              <mat-select [(ngModel)]="statusFilter">
                <mat-option value="all">All Status</mat-option>
                <mat-option value="pending">Pending</mat-option>
                <mat-option value="processing">Processing</mat-option>
                <mat-option value="approved">Approved</mat-option>
                <mat-option value="rejected">Rejected</mat-option>
              </mat-select>
              <mat-icon matPrefix>filter_list</mat-icon>
            </mat-form-field>
            
            <mat-form-field appearance="outline" class="w-48">
              <mat-label>Tenant</mat-label>
              <mat-select [(ngModel)]="tenantFilter">
                <mat-option value="all">All Tenants</mat-option>
                <mat-option value="PowerCell Industries">PowerCell Industries</mat-option>
                <mat-option value="EnergyMax Solutions">EnergyMax Solutions</mat-option>
                <mat-option value="BatteryTech Corp">BatteryTech Corp</mat-option>
              </mat-select>
              <mat-icon matPrefix>filter_list</mat-icon>
            </mat-form-field>
          </div>

          <div class="overflow-auto">
            <table mat-table [dataSource]="filteredClaims" class="w-full">
              <ng-container matColumnDef="id">
                <th mat-header-cell *matHeaderCellDef>Claim ID</th>
                <td mat-cell *matCellDef="let claim" class="font-medium">{{ claim.id }}</td>
              </ng-container>

              <ng-container matColumnDef="date">
                <th mat-header-cell *matHeaderCellDef>Date</th>
                <td mat-cell *matCellDef="let claim">{{ claim.date }}</td>
              </ng-container>

              <ng-container matColumnDef="customer">
                <th mat-header-cell *matHeaderCellDef>Customer</th>
                <td mat-cell *matCellDef="let claim">
                  <div>
                    <p class="font-medium">{{ claim.customer }}</p>
                    <p class="text-xs text-muted">{{ claim.phone }}</p>
                  </div>
                </td>
              </ng-container>

              <ng-container matColumnDef="tenant">
                <th mat-header-cell *matHeaderCellDef>Tenant</th>
                <td mat-cell *matCellDef="let claim">
                  <div>
                    <p class="font-medium">{{ claim.tenant }}</p>
                    <p class="text-xs text-muted">{{ claim.brand }}</p>
                  </div>
                </td>
              </ng-container>

              <ng-container matColumnDef="product">
                <th mat-header-cell *matHeaderCellDef>Product</th>
                <td mat-cell *matCellDef="let claim">
                  <div>
                    <p class="font-medium">{{ claim.product }}</p>
                    <p class="text-xs text-muted font-mono">{{ claim.serialNumber }}</p>
                  </div>
                </td>
              </ng-container>

              <ng-container matColumnDef="issue">
                <th mat-header-cell *matHeaderCellDef>Issue</th>
                <td mat-cell *matCellDef="let claim" class="max-w-48 truncate">{{ claim.issue }}</td>
              </ng-container>

              <ng-container matColumnDef="priority">
                <th mat-header-cell *matHeaderCellDef>Priority</th>
                <td mat-cell *matCellDef="let claim">
                  <mat-chip [color]="getPriorityColor(claim.priority)">{{ claim.priority }}</mat-chip>
                </td>
              </ng-container>

              <ng-container matColumnDef="status">
                <th mat-header-cell *matHeaderCellDef>Status</th>
                <td mat-cell *matCellDef="let claim">
                  <mat-chip [color]="getStatusColor(claim.status)">
                    <mat-icon class="text-xs mr-1">{{ getStatusIcon(claim.status) }}</mat-icon>
                    {{ claim.status }}
                  </mat-chip>
                </td>
              </ng-container>

              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef>Actions</th>
                <td mat-cell *matCellDef="let claim">
                  <button mat-stroked-button (click)="reviewClaim(claim)">
                    <mat-icon>visibility</mat-icon>
                    Review
                  </button>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
            </table>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `
})
export class PlatformClaimsManagementComponent {
  searchTerm = '';
  statusFilter = 'all';
  tenantFilter = 'all';
  displayedColumns = ['id', 'date', 'customer', 'tenant', 'product', 'issue', 'priority', 'status', 'actions'];

  claimsMetrics = [
    { label: 'Total Claims', value: '4', icon: 'schedule', change: '+12 from last week' },
    { label: 'Pending', value: '1', icon: 'warning', change: 'Requires attention' },
    { label: 'Approved', value: '1', icon: 'check_circle', change: 'This month' },
    { label: 'Rejected', value: '1', icon: 'cancel', change: 'This month' }
  ];

  claims = [
    {
      id: 'CLM-001',
      date: '2024-07-15',
      customer: 'Muhammad Ali',
      phone: '+92-300-1234567',
      tenant: 'PowerCell Industries',
      brand: 'Volta',
      product: 'VL120-45AH',
      serialNumber: 'VL120230001',
      purchaseDate: '2023-05-15',
      issue: 'Battery not holding charge',
      status: 'pending',
      priority: 'high',
      retailer: 'AutoMart Central'
    },
    {
      id: 'CLM-002',
      date: '2024-07-14',
      customer: 'Ayesha Khan',
      phone: '+92-301-2345678',
      tenant: 'EnergyMax Solutions',
      brand: 'Osaka',
      product: 'OS80-35AH',
      serialNumber: 'OS80230002',
      purchaseDate: '2023-08-20',
      issue: 'Physical damage to terminals',
      status: 'approved',
      priority: 'medium',
      retailer: 'Power Zone Lahore'
    }
  ];

  get filteredClaims() {
    return this.claims.filter(claim => {
      const matchesSearch = claim.customer.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
                           claim.id.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
                           claim.product.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
                           claim.tenant.toLowerCase().includes(this.searchTerm.toLowerCase());
      const matchesStatus = this.statusFilter === 'all' || claim.status === this.statusFilter;
      const matchesTenant = this.tenantFilter === 'all' || claim.tenant === this.tenantFilter;
      return matchesSearch && matchesStatus && matchesTenant;
    });
  }

  openCreateDialog(): void {
    console.log('Open create dialog');
  }

  reviewClaim(claim: any): void {
    console.log('Review claim:', claim);
  }

  getStatusColor(status: string): string {
    switch (status) {
      case 'pending': return 'primary';
      case 'processing': return 'accent';
      case 'approved': return 'primary';
      case 'rejected': return 'warn';
      default: return 'basic';
    }
  }

  getPriorityColor(priority: string): string {
    switch (priority) {
      case 'high': return 'warn';
      case 'medium': return 'primary';
      case 'low': return 'accent';
      default: return 'basic';
    }
  }

  getStatusIcon(status: string): string {
    switch (status) {
      case 'pending': return 'schedule';
      case 'processing': return 'warning';
      case 'approved': return 'check_circle';
      case 'rejected': return 'cancel';
      default: return 'schedule';
    }
  }
}
