// src/components/ui/page-header.tsx
import React from 'react';
import { cn } from '@/lib/utils';

interface PageHeaderProps {
  title: string;
  description?: string;
  action?: React.ReactNode;
  className?: string;
}

export const PageHeader: React.FC<PageHeaderProps> = ({
  title,
  description,
  action,
  className
}) => {
  return (
    <div className={cn('flex items-center justify-between pb-6 border-b border-border', className)}>
      <div className="space-y-1">
        <h1 className="text-page-title font-heading text-foreground">{title}</h1>
        {description && (
          <p className="text-body text-secondary-foreground">{description}</p>
        )}
      </div>
      {action && (
        <div className="flex items-center space-x-2">
          {action}
        </div>
      )}
    </div>
  );
};

// src/app/components/ui/page-header/page-header.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-page-header',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="flex items-center justify-between pb-6 border-b">
      <div class="space-y-1">
        <h1 class="text-3xl font-bold">{{ title }}</h1>
        <p *ngIf="description" class="text-lg text-muted">{{ description }}</p>
      </div>
      <div *ngIf="hasActionContent" class="flex items-center gap-2">
        <ng-content></ng-content>
      </div>
    </div>
  `
})
export class PageHeaderComponent {
  @Input() title!: string;
  @Input() description?: string;

  get hasActionContent(): boolean {
    return true; // Angular doesn't have a direct equivalent to React's children check
  }
}
