// src/pages/signup/CompanyInfo.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { Building2, ArrowRight, ArrowLeft } from 'lucide-react';

const CompanyInfo = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [subdomain, setSubdomain] = useState('');
  const [formData, setFormData] = useState({
    companyName: '',
    industry: '',
    contactPerson: '',
    email: '',
    phone: '',
    companySize: '',
    expectedVolume: ''
  });

  const industries = [
    'Electronics',
    'Automotive', 
    'Home Appliances',
    'Industrial Equipment',
    'Consumer Goods',
    'Technology',
    'Healthcare',
    'Manufacturing',
    'Other'
  ];

  const companySizes = [
    'Small (1-50 employees)',
    'Medium (51-200 employees)', 
    'Large (201-1000 employees)',
    'Enterprise (1000+ employees)'
  ];

  const expectedVolumes = [
    'Low (< 1,000 warranties/year)',
    'Medium (1,000 - 10,000 warranties/year)',
    'High (10,000 - 100,000 warranties/year)',
    'Enterprise (100,000+ warranties/year)'
  ];

  useEffect(() => {
    const urlSubdomain = searchParams.get('subdomain');
    const storedSubdomain = localStorage.getItem('selectedSubdomain');
    
    if (urlSubdomain) {
      setSubdomain(urlSubdomain);
      localStorage.setItem('selectedSubdomain', urlSubdomain);
    } else if (storedSubdomain) {
      setSubdomain(storedSubdomain);
    } else {
      // Redirect back to landing if no subdomain
      navigate('/');
    }

    // Load saved form data
    const savedData = localStorage.getItem('companyInfo');
    if (savedData) {
      setFormData(JSON.parse(savedData));
    }
  }, [searchParams, navigate]);

  const handleInputChange = (field: string, value: string) => {
    const updatedData = { ...formData, [field]: value };
    setFormData(updatedData);
    localStorage.setItem('companyInfo', JSON.stringify(updatedData));
  };

  const handleNext = () => {
    if (isFormValid()) {
      navigate('/signup/account-setup');
    }
  };

  const isFormValid = () => {
    return formData.companyName && 
           formData.industry && 
           formData.contactPerson && 
           formData.email && 
           formData.phone;
  };

  return (
    <div className="min-h-screen bg-page-background flex items-center justify-center p-4">
      <div className="w-full max-w-2xl">
        {/* Progress */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <h1 className="text-section-title font-heading text-card-foreground">
              Create Your Account
            </h1>
            <span className="text-body text-muted-foreground">
              Step 1 of 5
            </span>
          </div>
          <Progress value={20} className="h-2" />
        </div>

        <Card className="bg-card shadow-elegant border border-border">
          <CardHeader>
            <CardTitle className="flex items-center gap-3 text-card-title font-heading">
              <Building2 className="h-6 w-6 text-trust-blue" />
              Company Information
            </CardTitle>
            <p className="text-body text-muted-foreground">
              Setting up: <span className="font-medium text-trust-blue">{subdomain}.ewarranty.pk</span>
            </p>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-2">
                <Label htmlFor="companyName">Company Name *</Label>
                <Input
                  id="companyName"
                  value={formData.companyName}
                  onChange={(e) => handleInputChange('companyName', e.target.value)}
                  placeholder="Enter your company name"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="industry">Industry *</Label>
                <Select value={formData.industry} onValueChange={(value) => handleInputChange('industry', value)}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select industry" />
                  </SelectTrigger>
                  <SelectContent>
                    {industries.map((industry) => (
                      <SelectItem key={industry} value={industry}>
                        {industry}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="contactPerson">Contact Person *</Label>
                <Input
                  id="contactPerson"
                  value={formData.contactPerson}
                  onChange={(e) => handleInputChange('contactPerson', e.target.value)}
                  placeholder="Full name"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="email">Email Address *</Label>
                <Input
                  id="email"
                  type="email"
                  value={formData.email}
                  onChange={(e) => handleInputChange('email', e.target.value)}
                  placeholder="admin@yourcompany.com"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="phone">Phone Number *</Label>
                <Input
                  id="phone"
                  value={formData.phone}
                  onChange={(e) => handleInputChange('phone', e.target.value)}
                  placeholder="+92 300 1234567"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="companySize">Company Size</Label>
                <Select value={formData.companySize} onValueChange={(value) => handleInputChange('companySize', value)}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select company size" />
                  </SelectTrigger>
                  <SelectContent>
                    {companySizes.map((size) => (
                      <SelectItem key={size} value={size}>
                        {size}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="expectedVolume">Expected Warranty Volume</Label>
              <Select value={formData.expectedVolume} onValueChange={(value) => handleInputChange('expectedVolume', value)}>
                <SelectTrigger>
                  <SelectValue placeholder="Select expected warranty volume" />
                </SelectTrigger>
                <SelectContent>
                  {expectedVolumes.map((volume) => (
                    <SelectItem key={volume} value={volume}>
                      {volume}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="flex justify-between pt-6">
              <Button 
                variant="outline" 
                onClick={() => navigate('/')}
                className="flex items-center gap-2"
              >
                <ArrowLeft className="h-4 w-4" />
                Back to Home
              </Button>
              <Button 
                onClick={handleNext}
                disabled={!isFormValid()}
                className="bg-battery-green hover:bg-battery-green/90 flex items-center gap-2"
              >
                Continue
                <ArrowRight className="h-4 w-4" />
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default CompanyInfo;

// src/app/pages/signup/company-info/company-info.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';

@Component({
  selector: 'app-company-info',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatIconModule,
    MatProgressBarModule
  ],
  template: `
    <div class="min-h-screen bg-page-background flex items-center justify-center p-4">
      <div class="w-full max-w-2xl">
        <!-- Progress -->
        <div class="mb-8">
          <div class="flex items-center justify-between mb-4">
            <h1 class="text-3xl font-bold">Create Your Account</h1>
            <span class="text-muted">Step 1 of 5</span>
          </div>
          <mat-progress-bar mode="determinate" [value]="20"></mat-progress-bar>
        </div>

        <mat-card class="shadow-elegant">
          <mat-card-header>
            <mat-card-title class="flex items-center gap-3">
              <mat-icon class="text-trust-blue">business</mat-icon>
              Company Information
            </mat-card-title>
            <mat-card-subtitle>
              Setting up: <span class="font-medium text-trust-blue">{{ subdomain }}.ewarranty.pk</span>
            </mat-card-subtitle>
          </mat-card-header>
          
          <mat-card-content class="space-y-6">
            <form (ngSubmit)="handleNext()" #companyForm="ngForm">
              <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <mat-form-field appearance="outline" class="w-full">
                  <mat-label>Company Name *</mat-label>
                  <input matInput 
                         [(ngModel)]="formData.companyName" 
                         name="companyName"
                         placeholder="Enter your company name"
                         required>
                </mat-form-field>

                <mat-form-field appearance="outline" class="w-full">
                  <mat-label>Industry *</mat-label>
                  <mat-select [(ngModel)]="formData.industry" name="industry" required>
                    <mat-option *ngFor="let industry of industries" [value]="industry">
                      {{ industry }}
                    </mat-option>
                  </mat-select>
                </mat-form-field>

                <mat-form-field appearance="outline" class="w-full">
                  <mat-label>Contact Person *</mat-label>
                  <input matInput 
                         [(ngModel)]="formData.contactPerson" 
                         name="contactPerson"
                         placeholder="Full name"
                         required>
                </mat-form-field>

                <mat-form-field appearance="outline" class="w-full">
                  <mat-label>Email Address *</mat-label>
                  <input matInput 
                         type="email"
                         [(ngModel)]="formData.email" 
                         name="email"
                         placeholder="admin@yourcompany.com"
                         required>
                </mat-form-field>

                <mat-form-field appearance="outline" class="w-full">
                  <mat-label>Phone Number *</mat-label>
                  <input matInput 
                         [(ngModel)]="formData.phone" 
                         name="phone"
                         placeholder="+92 300 1234567"
                         required>
                </mat-form-field>

                <mat-form-field appearance="outline" class="w-full">
                  <mat-label>Company Size</mat-label>
                  <mat-select [(ngModel)]="formData.companySize" name="companySize">
                    <mat-option *ngFor="let size of companySizes" [value]="size">
                      {{ size }}
                    </mat-option>
                  </mat-select>
                </mat-form-field>
              </div>

              <mat-form-field appearance="outline" class="w-full">
                <mat-label>Expected Warranty Volume</mat-label>
                <mat-select [(ngModel)]="formData.expectedVolume" name="expectedVolume">
                  <mat-option *ngFor="let volume of expectedVolumes" [value]="volume">
                    {{ volume }}
                  </mat-option>
                </mat-select>
              </mat-form-field>

              <div class="flex justify-between pt-6">
                <button mat-stroked-button type="button" (click)="goBack()">
                  <mat-icon>arrow_back</mat-icon>
                  Back to Home
                </button>
                <button mat-raised-button 
                        color="primary" 
                        type="submit"
                        [disabled]="!companyForm.valid">
                  Continue
                  <mat-icon>arrow_forward</mat-icon>
                </button>
              </div>
            </form>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  `,
  styles: [`
    .shadow-elegant {
      box-shadow: var(--shadow-elegant);
    }
  `]
})
export class CompanyInfoComponent implements OnInit {
  subdomain = '';
  formData = {
    companyName: '',
    industry: '',
    contactPerson: '',
    email: '',
    phone: '',
    companySize: '',
    expectedVolume: ''
  };

  industries = [
    'Electronics', 'Automotive', 'Home Appliances', 'Industrial Equipment',
    'Consumer Goods', 'Technology', 'Healthcare', 'Manufacturing', 'Other'
  ];

  companySizes = [
    'Small (1-50 employees)', 'Medium (51-200 employees)', 
    'Large (201-1000 employees)', 'Enterprise (1000+ employees)'
  ];

  expectedVolumes = [
    'Low (< 1,000 warranties/year)', 'Medium (1,000 - 10,000 warranties/year)',
    'High (10,000 - 100,000 warranties/year)', 'Enterprise (100,000+ warranties/year)'
  ];

  constructor(
    private router: Router,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    const urlSubdomain = this.route.snapshot.queryParams['subdomain'];
    const storedSubdomain = localStorage.getItem('selectedSubdomain');
    
    if (urlSubdomain) {
      this.subdomain = urlSubdomain;
      localStorage.setItem('selectedSubdomain', urlSubdomain);
    } else if (storedSubdomain) {
      this.subdomain = storedSubdomain;
    } else {
      this.router.navigate(['/']);
    }

    // Load saved form data
    const savedData = localStorage.getItem('companyInfo');
    if (savedData) {
      this.formData = JSON.parse(savedData);
    }
  }

  handleNext(): void {
    localStorage.setItem('companyInfo', JSON.stringify(this.formData));
    this.router.navigate(['/signup/account-setup']);
  }

  goBack(): void {
    this.router.navigate(['/']);
  }
}
