// src/app/components/brand-selector/brand-selector.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { Observable } from 'rxjs';
import { BrandService } from '../../services/brand.service';
import { AuthService } from '../../services/auth.service';
import { Brand, User } from '../../types';

@Component({
  selector: 'app-brand-selector',
  standalone: true,
  imports: [
    CommonModule,
    MatButtonModule,
    MatMenuModule,
    MatIconModule,
    MatChipsModule
  ],
  template: `
    <div *ngIf="availableBrands.length > 1">
      <button mat-button [matMenuTriggerFor]="brandMenu" class="flex items-center gap-2">
        <div *ngIf="activeBrand$ | async as brand" class="flex items-center gap-2">
          <div class="w-3 h-3 rounded-full" [style.background-color]="brand.color"></div>
          <span class="font-medium">{{ brand.displayName }}</span>
        </div>
        <mat-icon>expand_more</mat-icon>
      </button>
      
      <mat-menu #brandMenu="matMenu" class="w-64">
        <div class="p-2">
          <p class="text-sm text-muted mb-2">Switch Brand</p>
          
          <button 
            *ngFor="let brand of availableBrands" 
            mat-menu-item 
            (click)="selectBrand(brand)"
            class="flex items-center justify-between w-full p-3">
            <div class="flex items-center gap-3">
              <div class="w-4 h-4 rounded-full" [style.background-color]="brand.color"></div>
              <div>
                <div class="flex items-center gap-2">
                  <span class="font-medium">{{ brand.displayName }}</span>
                  <mat-chip *ngIf="brand.id === '1'" color="primary" class="text-xs">
                    <mat-icon class="text-xs">star</mat-icon>
                    Primary
                  </mat-chip>
                </div>
                <span class="text-sm text-muted">@{{ brand.name }}</span>
              </div>
            </div>
            
            <mat-icon *ngIf="(activeBrand$ | async)?.id === brand.id" class="text-primary">
              check
            </mat-icon>
          </button>
        </div>
        
        <mat-divider></mat-divider>
        
        <button mat-menu-item routerLink="/platform/brands">
          <mat-icon>settings</mat-icon>
          <span>Manage Brands</span>
        </button>
      </mat-menu>
    </div>
  `
})
export class BrandSelectorComponent implements OnInit {
  user$: Observable<User | null>;
  brands$: Observable<Brand[]>;
  activeBrand$: Observable<Brand | null>;
  availableBrands: Brand[] = [];

  constructor(
    private brandService: BrandService,
    private authService: AuthService
  ) {
    this.user$ = this.authService.user$;
    this.brands$ = this.brandService.brands$;
    this.activeBrand$ = this.brandService.activeBrand$;
  }

  ngOnInit(): void {
    this.brands$.subscribe(brands => {
      this.user$.subscribe(user => {
        this.availableBrands = this.getAvailableBrands(brands, user);
      });
    });
  }

  private getAvailableBrands(brands: Brand[], user: User | null): Brand[] {
    if (!user) return [];
    
    // System admins and company admins can see all brands
    if (user.role === 'system-admin' || user.role === 'brand-admin') {
      return brands;
    }
    
    // Brand-specific users only see their assigned brand
    if (user.brandId) {
      return brands.filter(brand => brand.id === user.brandId);
    }
    
    return brands;
  }

  selectBrand(brand: Brand): void {
    this.brandService.setActiveBrand(brand);
  }
}

// src/components/BrandSelector.tsx
import React from 'react';
import { Check, ChevronDown, Crown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { 
  DropdownMenu, 
  DropdownMenuContent, 
  DropdownMenuItem, 
  DropdownMenuTrigger,
  DropdownMenuSeparator
} from '@/components/ui/dropdown-menu';
import { Badge } from '@/components/ui/badge';
import { useBrands } from '@/contexts/BrandContext';
import { useAuth } from '@/contexts/AuthContext';

interface BrandSelectorProps {
  className?: string;
}

export const BrandSelector: React.FC<BrandSelectorProps> = ({ className }) => {
  const { brands, activeBrand, setActiveBrand } = useBrands();
  const { user } = useAuth();

  // Filter brands based on user role
  const getAvailableBrands = () => {
    if (!user) return [];
    
    // System admins and company admins can see all brands
    if (user.role === 'system-admin' || user.role === 'brand-admin') {
      return brands;
    }
    
    // Brand-specific users only see their assigned brand
    if (user.brandId) {
      return brands.filter(brand => brand.id === user.brandId);
    }
    
    return brands;
  };

  const availableBrands = getAvailableBrands();

  // Don't show selector if user has access to only one brand
  if (availableBrands.length <= 1) {
    return null;
  }

  const handleBrandSelect = (brand: typeof activeBrand) => {
    setActiveBrand(brand);
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild className={className}>
        <Button 
          variant="outline" 
          className="h-9 px-3 flex items-center gap-2 border-border"
        >
          {activeBrand && (
            <>
              <div 
                className="w-3 h-3 rounded-full" 
                style={{ backgroundColor: activeBrand.color }}
              />
              <span className="text-body font-medium">
                {activeBrand.displayName}
              </span>
            </>
          )}
          <ChevronDown className="h-4 w-4 text-muted-foreground" />
        </Button>
      </DropdownMenuTrigger>
      
      <DropdownMenuContent align="end" className="w-64">
        <div className="p-2">
          <p className="text-small text-muted-foreground mb-2">Switch Brand</p>
          
          {availableBrands.map((brand) => (
            <DropdownMenuItem
              key={brand.id}
              onClick={() => handleBrandSelect(brand)}
              className="flex items-center justify-between p-3 cursor-pointer hover:bg-section-background rounded-md"
            >
              <div className="flex items-center gap-3">
                <div 
                  className="w-4 h-4 rounded-full" 
                  style={{ backgroundColor: brand.color }}
                />
                <div className="flex flex-col">
                  <div className="flex items-center gap-2">
                    <span className="text-body font-medium">
                      {brand.displayName}
                    </span>
                    {brand.id === '1' && ( // Assuming first brand is primary
                      <Badge className="bg-battery-green text-white flex items-center gap-1 text-xs">
                        <Crown className="h-2 w-2" />
                        Primary
                      </Badge>
                    )}
                  </div>
                  <span className="text-small text-muted-foreground">
                    @{brand.name}
                  </span>
                </div>
              </div>
              
              {activeBrand?.id === brand.id && (
                <Check className="h-4 w-4 text-battery-green" />
              )}
            </DropdownMenuItem>
          ))}
        </div>
        
        <DropdownMenuSeparator />
        
        <div className="p-2">
          <Button 
            variant="ghost" 
            size="sm" 
            className="w-full justify-start text-small"
            onClick={() => {
              // Navigate to brand management
              window.location.href = '/platform/brands';
            }}
          >
            Manage Brands
          </Button>
        </div>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
