// src/app/components/dashboard-redirect/dashboard-redirect.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { take } from 'rxjs';

@Component({
  selector: 'app-dashboard-redirect',
  standalone: true,
  template: `
    <div class="min-h-screen flex items-center justify-center">
      <div class="text-center">
        <div class="animate-spin h-8 w-8 border-2 border-primary border-t-transparent rounded-full mx-auto mb-4"></div>
        <p class="text-muted">Redirecting to your dashboard...</p>
      </div>
    </div>
  `
})
export class DashboardRedirectComponent implements OnInit {
  constructor(
    private authService: AuthService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.authService.user$.pipe(take(1)).subscribe(user => {
      if (!user) {
        this.router.navigate(['/login']);
        return;
      }

      // Route users to their appropriate dashboard based on role
      switch (user.role) {
        case 'system-admin':
          this.router.navigate(['/platform/dashboard']);
          break;
        case 'brand-admin':
          this.router.navigate(['/brandadmin/dashboard']);
          break;
        case 'manufacturing-plant':
          this.router.navigate(['/manufacturing/dashboard']);
          break;
        case 'plant-warehouse':
          this.router.navigate(['/warehouse/dashboard']);
          break;
        case 'brand-distributor':
          this.router.navigate(['/distributor/dashboard']);
          break;
        case 'brand-retailer':
          this.router.navigate(['/retailer/dashboard']);
          break;
        case 'customer':
          this.router.navigate(['/']);
          break;
        default:
          this.router.navigate(['/']);
          break;
      }
    });
  }
}

// src/components/DashboardRedirect.tsx

import React from 'react';
import { Navigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';

export const DashboardRedirect: React.FC = () => {
  const { user } = useAuth();

  if (!user) {
    return <Navigate to="/login" replace />;
  }

  // Route users to their appropriate dashboard based on role
  switch (user.role) {
    case 'system-admin':
      return <Navigate to="/platform/dashboard" replace />;
    case 'brand-admin':
      return <Navigate to="/brandadmin/dashboard" replace />;
    case 'manufacturing-plant':
      return <Navigate to="/manufacturing/dashboard" replace />;
    case 'plant-warehouse':
      return <Navigate to="/warehouse/dashboard" replace />;
    case 'brand-distributor':
      return <Navigate to="/distributor/dashboard" replace />;
    case 'brand-retailer':
      return <Navigate to="/retailer/dashboard" replace />;
    case 'customer':
      // For customers, we might want to redirect to a customer-specific page
      // For now, let's redirect to a general customer dashboard or home page
      return <Navigate to="/" replace />;
    default:
      // For any unknown roles, redirect to home
      return <Navigate to="/" replace />;
  }
};
