// src/app/components/subdomain-selector/subdomain-selector.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { Router } from '@angular/router';

@Component({
  selector: 'app-subdomain-selector',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatDialogModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule
  ],
  template: `
    <div class="p-6">
      <div class="text-center mb-6">
        <mat-icon class="text-6xl text-primary mb-4">public</mat-icon>
        <h2 class="text-2xl font-bold mb-2">Choose Your Subdomain</h2>
        <p class="text-muted">Get your custom warranty portal instantly</p>
      </div>

      <div class="space-y-4">
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Your Company Subdomain</mat-label>
          <input matInput 
                 [(ngModel)]="subdomain" 
                 placeholder="yourcompany"
                 (input)="onSubdomainChange()"
                 [disabled]="isChecking">
          <mat-hint>{{ subdomain }}.ewarranty.pk</mat-hint>
        </mat-form-field>

        <div *ngIf="subdomain" class="text-center">
          <p class="text-sm text-muted">
            Your portal will be: 
            <span class="font-medium text-primary">{{ subdomain }}.ewarranty.pk</span>
          </p>
        </div>

        <button 
          *ngIf="subdomain && !isAvailable" 
          mat-raised-button 
          color="primary" 
          class="w-full"
          (click)="checkAvailability()"
          [disabled]="isChecking">
          <mat-icon *ngIf="isChecking">refresh</mat-icon>
          <mat-icon *ngIf="!isChecking">public</mat-icon>
          {{ isChecking ? 'Checking...' : 'Check Availability' }}
        </button>

        <div *ngIf="isAvailable === true" class="space-y-4">
          <div class="flex items-center justify-center gap-2 text-success">
            <mat-icon>check_circle</mat-icon>
            <span class="font-medium">Available!</span>
          </div>
          <button 
            mat-raised-button 
            color="accent" 
            class="w-full"
            (click)="getStarted()">
            Get Started with {{ subdomain }}.ewarranty.pk
          </button>
        </div>

        <div *ngIf="isAvailable === false" class="space-y-4">
          <div class="text-center text-destructive">
            <span class="font-medium">Not available or invalid</span>
            <p class="text-sm text-muted mt-1">
              Subdomains must be at least 3 characters and cannot be reserved words
            </p>
          </div>
          <div *ngIf="suggestions.length > 0" class="space-y-2">
            <p class="text-sm text-muted text-center">Try these suggestions:</p>
            <div class="flex flex-wrap gap-2 justify-center">
              <button 
                *ngFor="let suggestion of suggestions"
                mat-stroked-button
                color="primary"
                (click)="selectSuggestion(suggestion)">
                {{ suggestion }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  `
})
export class SubdomainSelectorComponent {
  subdomain = '';
  isChecking = false;
  isAvailable: boolean | null = null;
  suggestions: string[] = [];

  constructor(
    private dialogRef: MatDialogRef<SubdomainSelectorComponent>,
    private router: Router
  ) {}

  onSubdomainChange(): void {
    this.subdomain = this.subdomain.toLowerCase().replace(/[^a-z0-9-]/g, '');
    this.isAvailable = null;
    this.suggestions = [];
  }

  async checkAvailability(): Promise<void> {
    if (!this.subdomain.trim()) return;
    
    this.isChecking = true;
    
    // Simulate API call with validation
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const cleanSubdomain = this.subdomain.trim().toLowerCase();
    
    // Basic validation
    if (cleanSubdomain.length < 3) {
      this.isAvailable = false;
      this.suggestions = [`${cleanSubdomain}corp`, `${cleanSubdomain}company`, `${cleanSubdomain}inc`];
    } else if (['admin', 'api', 'www'].includes(cleanSubdomain)) {
      this.isAvailable = false;
      this.suggestions = [`${cleanSubdomain}corp`, `${cleanSubdomain}company`, `my${cleanSubdomain}`];
    } else {
      this.isAvailable = true;
      this.suggestions = [];
    }
    
    this.isChecking = false;
  }

  selectSuggestion(suggestion: string): void {
    this.subdomain = suggestion;
    this.isAvailable = null;
    this.suggestions = [];
  }

  getStarted(): void {
    if (this.subdomain.trim()) {
      localStorage.setItem('selectedSubdomain', this.subdomain.trim());
      this.dialogRef.close();
      this.router.navigate(['/signup/company-info'], { 
        queryParams: { subdomain: this.subdomain.trim() } 
      });
    }
  }
}

// src/components/SubdomainSelector.tsx

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, Globe, X } from 'lucide-react';

interface SubdomainSelectorProps {
  onSelect?: (subdomain: string) => void;
  onClose?: () => void;
}

export const SubdomainSelector: React.FC<SubdomainSelectorProps> = ({ onSelect, onClose }) => {
  const [subdomain, setSubdomain] = useState('');
  const [isChecking, setIsChecking] = useState(false);
  const [isAvailable, setIsAvailable] = useState<boolean | null>(null);
  const [suggestions, setSuggestions] = useState<string[]>([]);

  const checkAvailability = async () => {
    if (!subdomain.trim()) return;
    
    setIsChecking(true);
    // Simulate API call with validation
    setTimeout(() => {
      const cleanSubdomain = subdomain.trim().toLowerCase();
      
      // Basic validation
      if (cleanSubdomain.length < 3) {
        setIsAvailable(false);
        setSuggestions([`${cleanSubdomain}corp`, `${cleanSubdomain}company`, `${cleanSubdomain}inc`]);
      } else if (cleanSubdomain === 'admin' || cleanSubdomain === 'api' || cleanSubdomain === 'www') {
        setIsAvailable(false);
        setSuggestions([`${cleanSubdomain}corp`, `${cleanSubdomain}company`, `my${cleanSubdomain}`]);
      } else {
        setIsAvailable(true);
        setSuggestions([]);
      }
      
      setIsChecking(false);
    }, 1000);
  };

  const handleGetStarted = () => {
    if (subdomain.trim()) {
      // Store subdomain in localStorage for the signup flow
      localStorage.setItem('selectedSubdomain', subdomain.trim());
      
      // Navigate to company info page
      window.location.href = `/signup/company-info?subdomain=${subdomain.trim()}`;
      
      if (onSelect) {
        onSelect(subdomain.trim());
      }
    }
  };

  return (
    <Card className="bg-card shadow-elegant border border-border max-w-lg mx-auto relative z-50">
      {onClose && (
        <Button
          variant="ghost"
          size="sm"
          onClick={onClose}
          className="absolute top-4 right-4 z-10 h-8 w-8 p-0 hover:bg-muted"
        >
          <X className="h-4 w-4" />
        </Button>
      )}
      <CardHeader className="text-center">
        <CardTitle className="text-card-title font-heading text-card-foreground">
          Choose Your Subdomain
        </CardTitle>
        <p className="text-body text-muted-foreground">
          Get your custom warranty portal instantly
        </p>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <div className="flex items-center space-x-2">
            <Input
              placeholder="yourcompany"
              value={subdomain}
              onChange={(e) => {
                setSubdomain(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ''));
                setIsAvailable(null);
              }}
              className="text-center text-lg bg-input border-border"
            />
            <span className="text-body text-muted-foreground whitespace-nowrap">
              .ewarranty.pk
            </span>
          </div>
          {subdomain && (
            <div className="text-center">
              <p className="text-small text-muted-foreground">
                Your portal will be: <span className="font-medium text-trust-blue">
                  {subdomain}.ewarranty.pk
                </span>
              </p>
            </div>
          )}
        </div>

        {subdomain.trim() && (
          <div className="space-y-4">
            <Button
              onClick={checkAvailability}
              disabled={isChecking}
              className="w-full bg-trust-blue hover:bg-trust-blue/90 text-trust-blue-foreground"
            >
              <Globe className="mr-2 h-4 w-4" />
              {isChecking ? 'Checking...' : 'Check Availability'}
            </Button>

            {isAvailable === true && (
              <div className="space-y-4">
                <div className="flex items-center justify-center space-x-2 text-success">
                  <CheckCircle className="h-5 w-5" />
                  <span className="text-body font-medium">Available!</span>
                </div>
                <Button
                  onClick={handleGetStarted}
                  className="w-full bg-energy-yellow text-energy-yellow-foreground hover:bg-energy-yellow/90"
                  size="lg"
                >
                  Get Started with {subdomain}.ewarranty.pk
                </Button>
              </div>
            )}

            {isAvailable === false && (
              <div className="space-y-4">
                <div className="text-center text-error">
                  <span className="text-body font-medium">Not available or invalid</span>
                  <p className="text-small text-muted-foreground mt-1">
                    Subdomains must be at least 3 characters and cannot be reserved words
                  </p>
                </div>
                {suggestions.length > 0 && (
                  <div className="space-y-2">
                    <p className="text-small text-muted-foreground text-center">Try these suggestions:</p>
                    <div className="flex flex-wrap gap-2 justify-center">
                      {suggestions.map((suggestion, index) => (
                        <Button
                          key={index}
                          variant="outline"
                          size="sm"
                          onClick={() => {
                            setSubdomain(suggestion);
                            setIsAvailable(null);
                          }}
                          className="text-trust-blue border-trust-blue hover:bg-trust-blue/10"
                        >
                          {suggestion}
                        </Button>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
};
