// src/app/pages/platform/brand-management/brand-management.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatChipsModule } from '@angular/material/chips';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Observable } from 'rxjs';
import { BrandService } from '../../../services/brand.service';
import { Brand } from '../../../types';
import { PageHeaderComponent } from '../../../components/ui/page-header/page-header.component';

@Component({
  selector: 'app-platform-brand-management',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatDialogModule,
    MatChipsModule,
    PageHeaderComponent
  ],
  template: `
    <div class="space-y-6">
      <app-page-header
        title="Platform Brand Management"
        description="Manage brands across all tenant organizations">
        <button mat-raised-button color="primary" (click)="openCreateDialog()">
          <mat-icon>add</mat-icon>
          Add Brand
        </button>
      </app-page-header>

      <!-- Brand Cards Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <mat-card *ngFor="let brand of brands$ | async" 
                  class="shadow-elegant hover:shadow-glow transition-all duration-300">
          <mat-card-header class="pb-3">
            <div class="flex items-center justify-between w-full">
              <div class="flex items-center gap-3">
                <div class="w-6 h-6 rounded-full shadow-sm" [style.background-color]="brand.color"></div>
                <mat-card-title class="text-lg">{{ brand.displayName }}</mat-card-title>
              </div>
              <mat-chip [color]="brand.isActive ? 'primary' : 'basic'">
                <mat-icon class="text-xs mr-1">{{ brand.isActive ? 'check_circle' : 'cancel' }}</mat-icon>
                {{ brand.isActive ? 'Active' : 'Inactive' }}
              </mat-chip>
            </div>
          </mat-card-header>
          
          <mat-card-content class="space-y-4">
            <div class="space-y-2">
              <div class="flex justify-between text-sm">
                <span class="text-muted">URL Name:</span>
                <span class="font-mono bg-muted px-2 py-1 rounded text-xs">{{ brand.name }}</span>
              </div>
              <div class="flex justify-between text-sm">
                <span class="text-muted">Color:</span>
                <span class="font-mono text-xs">{{ brand.color }}</span>
              </div>
              <div class="flex justify-between text-sm">
                <span class="text-muted">Created:</span>
                <span class="text-xs">{{ brand.createdAt | date }}</span>
              </div>
            </div>

            <div class="flex justify-between items-center pt-2 border-t">
              <button mat-stroked-button 
                      (click)="toggleBrandStatus(brand)"
                      class="text-xs">
                {{ brand.isActive ? 'Deactivate' : 'Activate' }}
              </button>
              
              <div class="flex gap-1">
                <button mat-icon-button (click)="editBrand(brand)">
                  <mat-icon>edit</mat-icon>
                </button>
                <button mat-icon-button 
                        color="warn"
                        (click)="deleteBrand(brand)">
                  <mat-icon>delete</mat-icon>
                </button>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  `,
  styles: [`
    .shadow-elegant {
      box-shadow: var(--shadow-elegant);
    }
    
    .shadow-glow {
      box-shadow: var(--shadow-glow);
    }
  `]
})
export class PlatformBrandManagementComponent implements OnInit {
  brands$: Observable<Brand[]>;

  constructor(
    private brandService: BrandService,
    private dialog: MatDialog,
    private snackBar: MatSnackBar
  ) {
    this.brands$ = this.brandService.brands$;
  }

  ngOnInit(): void {}

  openCreateDialog(): void {
    // Implementation for create brand dialog
    console.log('Open create brand dialog');
  }

  editBrand(brand: Brand): void {
    // Implementation for edit brand dialog
    console.log('Edit brand:', brand);
  }

  deleteBrand(brand: Brand): void {
    if (confirm(`Are you sure you want to delete ${brand.displayName}?`)) {
      this.brandService.deleteBrand(brand.id);
      this.snackBar.open('Brand deleted successfully', 'Close', { duration: 3000 });
    }
  }

  toggleBrandStatus(brand: Brand): void {
    this.brandService.updateBrand(brand.id, { isActive: !brand.isActive });
    this.snackBar.open(
      `Brand ${brand.isActive ? 'deactivated' : 'activated'} successfully`, 
      'Close', 
      { duration: 3000 }
    );
  }
}

// src/pages/platform/BrandManagement.tsx

import React, { useState } from 'react';
import { PageHeader } from '@/components/ui/page-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Plus, Edit, Trash2, CheckCircle, XCircle } from 'lucide-react';
import { useBrands } from '@/contexts/BrandContext';
import { Brand } from '@/types';
import { useToast } from '@/hooks/use-toast';

const PlatformBrandManagement = () => {
  const { brands, addBrand, updateBrand, deleteBrand } = useBrands();
  const { toast } = useToast();
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [editingBrand, setEditingBrand] = useState<Brand | null>(null);
  const [formData, setFormData] = useState({
    name: '',
    displayName: '',
    color: '#3B82F6'
  });

  const resetForm = () => {
    setFormData({
      name: '',
      displayName: '',
      color: '#3B82F6'
    });
  };

  const handleCreate = () => {
    if (!formData.name || !formData.displayName) {
      toast({
        title: "Error",
        description: "Please fill in all required fields",
        variant: "destructive"
      });
      return;
    }

    addBrand({
      name: formData.name.toLowerCase().replace(/\s+/g, '-'),
      displayName: formData.displayName,
      color: formData.color,
      isActive: true
    });

    toast({
      title: "Success",
      description: "Brand created successfully"
    });

    resetForm();
    setIsCreateOpen(false);
  };

  const handleEdit = (brand: Brand) => {
    setEditingBrand(brand);
    setFormData({
      name: brand.name,
      displayName: brand.displayName,
      color: brand.color
    });
  };

  const handleUpdate = () => {
    if (!editingBrand) return;

    updateBrand(editingBrand.id, {
      name: formData.name.toLowerCase().replace(/\s+/g, '-'),
      displayName: formData.displayName,
      color: formData.color
    });

    toast({
      title: "Success",
      description: "Brand updated successfully"
    });

    setEditingBrand(null);
    resetForm();
  };

  const handleDelete = (brand: Brand) => {
    if (window.confirm(`Are you sure you want to delete ${brand.displayName}?`)) {
      deleteBrand(brand.id);
      toast({
        title: "Success",
        description: "Brand deleted successfully"
      });
    }
  };

  const toggleBrandStatus = (brand: Brand) => {
    updateBrand(brand.id, { isActive: !brand.isActive });
    toast({
      title: "Success",
      description: `Brand ${brand.isActive ? 'deactivated' : 'activated'} successfully`
    });
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Platform Brand Management"
        description="Manage brands across all tenant organizations"
        action={
          <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
            <DialogTrigger asChild>
              <Button className="bg-gradient-primary hover:shadow-glow">
                <Plus className="h-4 w-4 mr-2" />
                Add Brand
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New Brand</DialogTitle>
              </DialogHeader>
              <div className="space-y-4">
                <div>
                  <Label htmlFor="name">Brand Name (URL)</Label>
                  <Input
                    id="name"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    placeholder="e.g., volta"
                  />
                </div>
                <div>
                  <Label htmlFor="displayName">Display Name</Label>
                  <Input
                    id="displayName"
                    value={formData.displayName}
                    onChange={(e) => setFormData({ ...formData, displayName: e.target.value })}
                    placeholder="e.g., Volta"
                  />
                </div>
                <div>
                  <Label htmlFor="color">Brand Color</Label>
                  <div className="flex items-center space-x-2">
                    <Input
                      id="color"
                      type="color"
                      value={formData.color}
                      onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                      className="w-16 h-10"
                    />
                    <Input
                      value={formData.color}
                      onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                      placeholder="#3B82F6"
                    />
                  </div>
                </div>
                <div className="flex justify-end space-x-2">
                  <Button variant="outline" onClick={() => setIsCreateOpen(false)}>
                    Cancel
                  </Button>
                  <Button onClick={handleCreate} className="bg-gradient-primary">
                    Create Brand
                  </Button>
                </div>
              </div>
            </DialogContent>
          </Dialog>
        }
      />

      {/* Brand Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {brands.map((brand) => (
          <Card key={brand.id} className="bg-gradient-card shadow-elegant hover:shadow-glow transition-all duration-300">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-3">
                  <div 
                    className="w-6 h-6 rounded-full shadow-sm"
                    style={{ backgroundColor: brand.color }}
                  />
                  <CardTitle className="text-lg">{brand.displayName}</CardTitle>
                </div>
                <Badge 
                  variant={brand.isActive ? "default" : "secondary"}
                  className={brand.isActive ? "bg-green-100 text-green-800" : ""}
                >
                  {brand.isActive ? (
                    <CheckCircle className="h-3 w-3 mr-1" />
                  ) : (
                    <XCircle className="h-3 w-3 mr-1" />
                  )}
                  {brand.isActive ? 'Active' : 'Inactive'}
                </Badge>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">URL Name:</span>
                  <span className="font-mono bg-muted px-2 py-1 rounded text-xs">
                    {brand.name}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Color:</span>
                  <span className="font-mono text-xs">{brand.color}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Created:</span>
                  <span className="text-xs">
                    {brand.createdAt.toLocaleDateString()}
                  </span>
                </div>
              </div>

              <div className="flex justify-between items-center pt-2 border-t border-border">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => toggleBrandStatus(brand)}
                  className="text-xs"
                >
                  {brand.isActive ? 'Deactivate' : 'Activate'}
                </Button>
                
                <div className="flex space-x-1">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleEdit(brand)}
                  >
                    <Edit className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleDelete(brand)}
                    className="text-destructive hover:text-destructive"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Edit Dialog */}
      <Dialog open={!!editingBrand} onOpenChange={() => setEditingBrand(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Brand</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label htmlFor="edit-name">Brand Name (URL)</Label>
              <Input
                id="edit-name"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder="e.g., volta"
              />
            </div>
            <div>
              <Label htmlFor="edit-displayName">Display Name</Label>
              <Input
                id="edit-displayName"
                value={formData.displayName}
                onChange={(e) => setFormData({ ...formData, displayName: e.target.value })}
                placeholder="e.g., Volta"
              />
            </div>
            <div>
              <Label htmlFor="edit-color">Brand Color</Label>
              <div className="flex items-center space-x-2">
                <Input
                  id="edit-color"
                  type="color"
                  value={formData.color}
                  onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                  className="w-16 h-10"
                />
                <Input
                  value={formData.color}
                  onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                  placeholder="#3B82F6"
                />
              </div>
            </div>
            <div className="flex justify-end space-x-2">
              <Button variant="outline" onClick={() => setEditingBrand(null)}>
                Cancel
              </Button>
              <Button onClick={handleUpdate} className="bg-gradient-primary">
                Update Brand
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default PlatformBrandManagement;
