// src/app/pages/platform/distributors-management/distributors-management.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { PageHeaderComponent } from '../../../components/ui/page-header/page-header.component';
import { MetricCardComponent } from '../../../components/ui/metric-card/metric-card.component';

@Component({
  selector: 'app-platform-distributors-management',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatTableModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatIconModule,
    MatChipsModule,
    PageHeaderComponent,
    MetricCardComponent
  ],
  template: `
    <div class="space-y-6">
      <app-page-header
        title="Platform Distributors Management" 
        description="Manage distributor network across all tenant organizations">
        <button mat-raised-button color="primary">
          <mat-icon>add</mat-icon>
          Add Distributor
        </button>
      </app-page-header>

      <div class="grid grid-cols-1 md:grid-cols-4 gap-6">
        <app-metric-card
          *ngFor="let metric of distributorMetrics"
          [title]="metric.label"
          [value]="metric.value"
          [icon]="metric.icon"
          [change]="metric.change">
        </app-metric-card>
      </div>

      <mat-card>
        <mat-card-header>
          <mat-card-title>Platform Distributor Network</mat-card-title>
          <mat-card-subtitle>Manage distributor partnerships and performance across all tenants</mat-card-subtitle>
        </mat-card-header>
        <mat-card-content>
          <div class="flex gap-4 mb-6">
            <mat-form-field appearance="outline" class="flex-1">
              <mat-label>Search</mat-label>
              <input matInput 
                     [(ngModel)]="searchTerm"
                     placeholder="Search distributors...">
              <mat-icon matPrefix>search</mat-icon>
            </mat-form-field>
            
            <mat-form-field appearance="outline" class="w-48">
              <mat-label>Filter by Tenant</mat-label>
              <mat-select [(ngModel)]="tenantFilter">
                <mat-option value="all">All Tenants</mat-option>
                <mat-option value="PowerCell Industries">PowerCell Industries</mat-option>
                <mat-option value="EnergyMax Solutions">EnergyMax Solutions</mat-option>
                <mat-option value="BatteryTech Corp">BatteryTech Corp</mat-option>
              </mat-select>
              <mat-icon matPrefix>business</mat-icon>
            </mat-form-field>
          </div>

          <div class="overflow-auto">
            <table mat-table [dataSource]="filteredDistributors" class="w-full">
              <ng-container matColumnDef="name">
                <th mat-header-cell *matHeaderCellDef>Distributor</th>
                <td mat-cell *matCellDef="let distributor">
                  <div>
                    <p class="font-medium">{{ distributor.name }}</p>
                    <p class="text-sm text-muted">{{ distributor.id }}</p>
                  </div>
                </td>
              </ng-container>

              <ng-container matColumnDef="contact">
                <th mat-header-cell *matHeaderCellDef>Contact</th>
                <td mat-cell *matCellDef="let distributor">
                  <div class="space-y-1">
                    <p class="font-medium">{{ distributor.contact }}</p>
                    <div class="flex items-center gap-1 text-xs text-muted">
                      <mat-icon class="text-xs">phone</mat-icon>
                      <span>{{ distributor.phone }}</span>
                    </div>
                    <div class="flex items-center gap-1 text-xs text-muted">
                      <mat-icon class="text-xs">email</mat-icon>
                      <span>{{ distributor.email }}</span>
                    </div>
                  </div>
                </td>
              </ng-container>

              <ng-container matColumnDef="tenant">
                <th mat-header-cell *matHeaderCellDef>Tenant</th>
                <td mat-cell *matCellDef="let distributor">
                  <div class="flex items-center gap-1">
                    <mat-icon class="text-xs text-muted">business</mat-icon>
                    <span>{{ distributor.tenant }}</span>
                  </div>
                </td>
              </ng-container>

              <ng-container matColumnDef="location">
                <th mat-header-cell *matHeaderCellDef>Location</th>
                <td mat-cell *matCellDef="let distributor">
                  <div class="flex items-center gap-1">
                    <mat-icon class="text-xs text-muted">place</mat-icon>
                    <span>{{ distributor.location }}</span>
                  </div>
                </td>
              </ng-container>

              <ng-container matColumnDef="brands">
                <th mat-header-cell *matHeaderCellDef>Brands</th>
                <td mat-cell *matCellDef="let distributor">
                  <div class="flex flex-wrap gap-1">
                    <mat-chip *ngFor="let brand of distributor.brands" class="text-xs">{{ brand }}</mat-chip>
                  </div>
                </td>
              </ng-container>

              <ng-container matColumnDef="retailers">
                <th mat-header-cell *matHeaderCellDef>Retailers</th>
                <td mat-cell *matCellDef="let distributor">{{ distributor.retailers }}</td>
              </ng-container>

              <ng-container matColumnDef="volume">
                <th mat-header-cell *matHeaderCellDef>Monthly Volume</th>
                <td mat-cell *matCellDef="let distributor">{{ distributor.monthlyVolume | number }}</td>
              </ng-container>

              <ng-container matColumnDef="performance">
                <th mat-header-cell *matHeaderCellDef>Performance</th>
                <td mat-cell *matCellDef="let distributor">
                  <mat-chip [color]="getPerformanceColor(distributor.performance)">{{ distributor.performance }}</mat-chip>
                </td>
              </ng-container>

              <ng-container matColumnDef="status">
                <th mat-header-cell *matHeaderCellDef>Status</th>
                <td mat-cell *matCellDef="let distributor">
                  <mat-chip [color]="getStatusColor(distributor.status)">{{ distributor.status }}</mat-chip>
                </td>
              </ng-container>

              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef>Actions</th>
                <td mat-cell *matCellDef="let distributor">
                  <div class="flex gap-1">
                    <button mat-icon-button><mat-icon>edit</mat-icon></button>
                    <button mat-icon-button><mat-icon>delete</mat-icon></button>
                  </div>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
            </table>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `
})
export class PlatformDistributorsManagementComponent {
  searchTerm = '';
  tenantFilter = 'all';
  displayedColumns = ['name', 'contact', 'tenant', 'location', 'brands', 'retailers', 'volume', 'performance', 'status', 'actions'];

  distributorMetrics = [
    { label: 'Total Distributors', value: '4', icon: 'people', change: '+2 from last month' },
    { label: 'Active', value: '3', icon: 'people', change: 'Currently operating' },
    { label: 'Total Retailers', value: '83', icon: 'people', change: 'Network reach' },
    { label: 'Monthly Volume', value: '7,900', icon: 'people', change: 'Units distributed' }
  ];

  distributors = [
    {
      id: 'DIST-001',
      name: 'Metro Auto Distributors',
      contact: 'Tariq Ahmad',
      phone: '+92-300-1234567',
      email: 'tariq@metroauto.pk',
      location: 'Lahore',
      tenant: 'PowerCell Industries',
      brands: ['Volta', 'Osaka'],
      status: 'active',
      retailers: 25,
      monthlyVolume: 2500,
      performance: 'excellent'
    },
    {
      id: 'DIST-002',
      name: 'Power Solutions Hub',
      contact: 'Sadia Khan',
      phone: '+92-301-2345678',
      email: 'sadia@powersolutions.pk',
      location: 'Karachi',
      tenant: 'EnergyMax Solutions',
      brands: ['Fujika', 'SAGA'],
      status: 'active',
      retailers: 18,
      monthlyVolume: 1800,
      performance: 'good'
    }
  ];

  get filteredDistributors() {
    return this.distributors.filter(distributor => {
      const matchesSearch = distributor.name.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
                           distributor.contact.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
                           distributor.location.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
                           distributor.tenant.toLowerCase().includes(this.searchTerm.toLowerCase());
      const matchesTenant = this.tenantFilter === 'all' || distributor.tenant === this.tenantFilter;
      return matchesSearch && matchesTenant;
    });
  }

  getStatusColor(status: string): string {
    return status === 'active' ? 'primary' : 'accent';
  }

  getPerformanceColor(performance: string): string {
    switch (performance) {
      case 'excellent': return 'primary';
      case 'good': return 'accent';
      case 'poor': return 'warn';
      default: return 'basic';
    }
  }
}

// src/pages/platform/DistributorsManagement.tsx

import React, { useState } from 'react';
import { PageHeader } from '@/components/ui/page-header';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Search, Plus, Edit, Trash2, Users, MapPin, Phone, Mail, Building2 } from 'lucide-react';

export const PlatformDistributorsManagement: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [tenantFilter, setTenantFilter] = useState('all');
  const [isAddDistributorOpen, setIsAddDistributorOpen] = useState(false);

  const distributors = [
    {
      id: 'DIST-001',
      name: 'Metro Auto Distributors',
      contact: 'Tariq Ahmad',
      phone: '+92-300-1234567',
      email: 'tariq@metroauto.pk',
      location: 'Lahore',
      tenant: 'PowerCell Industries',
      brands: ['Volta', 'Osaka'],
      status: 'active',
      retailers: 25,
      monthlyVolume: 2500,
      performance: 'excellent'
    },
    {
      id: 'DIST-002',
      name: 'Power Solutions Hub',
      contact: 'Sadia Khan',
      phone: '+92-301-2345678',
      email: 'sadia@powersolutions.pk',
      location: 'Karachi',
      tenant: 'EnergyMax Solutions',
      brands: ['Fujika', 'SAGA'],
      status: 'active',
      retailers: 18,
      monthlyVolume: 1800,
      performance: 'good'
    },
    {
      id: 'DIST-003',
      name: 'Elite Battery Network',
      contact: 'Hassan Ali',
      phone: '+92-302-3456789',
      email: 'hassan@elitebattery.pk',
      location: 'Islamabad',
      tenant: 'BatteryTech Corp',
      brands: ['Volta', 'Fujika', 'Osaka', 'SAGA'],
      status: 'active',
      retailers: 32,
      monthlyVolume: 3200,
      performance: 'excellent'
    },
    {
      id: 'DIST-004',
      name: 'City Auto Parts',
      contact: 'Fatima Sheikh',
      phone: '+92-303-4567890',
      email: 'fatima@cityauto.pk',
      location: 'Faisalabad',
      tenant: 'PowerCell Industries',
      brands: ['Osaka'],
      status: 'inactive',
      retailers: 8,
      monthlyVolume: 400,
      performance: 'poor'
    }
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'default';
      case 'inactive': return 'secondary';
      default: return 'outline';
    }
  };

  const getPerformanceColor = (performance: string) => {
    switch (performance) {
      case 'excellent': return 'default';
      case 'good': return 'secondary';
      case 'poor': return 'destructive';
      default: return 'outline';
    }
  };

  const filteredDistributors = distributors.filter(distributor => {
    const matchesSearch = distributor.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         distributor.contact.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         distributor.location.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         distributor.tenant.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesTenant = tenantFilter === 'all' || distributor.tenant === tenantFilter;
    return matchesSearch && matchesTenant;
  });

  return (
    <div className="space-y-6">
      <PageHeader
        title="Platform Distributors Management" 
        description="Manage distributor network across all tenant organizations"
        action={
          <Dialog open={isAddDistributorOpen} onOpenChange={setIsAddDistributorOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="h-4 w-4 mr-2" />
                Add Distributor
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[600px]">
              <DialogHeader>
                <DialogTitle>Add New Distributor</DialogTitle>
                <DialogDescription>
                  Register a new distributor to the platform network
                </DialogDescription>
              </DialogHeader>
              <div className="grid grid-cols-2 gap-4 py-4">
                <div className="space-y-2">
                  <Label htmlFor="dist-name">Company Name</Label>
                  <Input id="dist-name" placeholder="Enter company name" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="contact-person">Contact Person</Label>
                  <Input id="contact-person" placeholder="Contact person name" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="phone">Phone Number</Label>
                  <Input id="phone" placeholder="+92-XXX-XXXXXXX" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email Address</Label>
                  <Input id="email" type="email" placeholder="email@company.pk" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="tenant">Tenant Organization</Label>
                  <Select>
                    <SelectTrigger>
                      <SelectValue placeholder="Select tenant" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="powercell">PowerCell Industries</SelectItem>
                      <SelectItem value="energymax">EnergyMax Solutions</SelectItem>
                      <SelectItem value="batterytech">BatteryTech Corp</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="location">Location</Label>
                  <Select>
                    <SelectTrigger>
                      <SelectValue placeholder="Select city" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="lahore">Lahore</SelectItem>
                      <SelectItem value="karachi">Karachi</SelectItem>
                      <SelectItem value="islamabad">Islamabad</SelectItem>
                      <SelectItem value="faisalabad">Faisalabad</SelectItem>
                      <SelectItem value="rawalpindi">Rawalpindi</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="flex justify-end gap-2">
                <Button variant="outline" onClick={() => setIsAddDistributorOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={() => setIsAddDistributorOpen(false)}>
                  Add Distributor
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        }
      />

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Distributors</CardTitle>
            <Users className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{distributors.length}</div>
            <p className="text-xs text-muted-foreground">+2 from last month</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Active</CardTitle>
            <Users className="h-4 w-4 text-success" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {distributors.filter(d => d.status === 'active').length}
            </div>
            <p className="text-xs text-muted-foreground">Currently operating</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Total Retailers</CardTitle>
            <Users className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {distributors.reduce((sum, d) => sum + d.retailers, 0)}
            </div>
            <p className="text-xs text-muted-foreground">Network reach</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">Monthly Volume</CardTitle>
            <Users className="h-4 w-4 text-primary" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {distributors.reduce((sum, d) => sum + d.monthlyVolume, 0).toLocaleString()}
            </div>
            <p className="text-xs text-muted-foreground">Units distributed</p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Platform Distributor Network</CardTitle>
          <CardDescription>Manage distributor partnerships and performance across all tenants</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4 mb-6">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search distributors..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={tenantFilter} onValueChange={setTenantFilter}>
              <SelectTrigger className="w-48">
                <Building2 className="h-4 w-4 mr-2" />
                <SelectValue placeholder="Filter by tenant" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Tenants</SelectItem>
                <SelectItem value="PowerCell Industries">PowerCell Industries</SelectItem>
                <SelectItem value="EnergyMax Solutions">EnergyMax Solutions</SelectItem>
                <SelectItem value="BatteryTech Corp">BatteryTech Corp</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Distributor</TableHead>
                  <TableHead>Contact</TableHead>
                  <TableHead>Tenant</TableHead>
                  <TableHead>Location</TableHead>
                  <TableHead>Brands</TableHead>
                  <TableHead>Retailers</TableHead>
                  <TableHead>Monthly Volume</TableHead>
                  <TableHead>Performance</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredDistributors.map((distributor) => (
                  <TableRow key={distributor.id}>
                    <TableCell>
                      <div>
                        <p className="font-medium">{distributor.name}</p>
                        <p className="text-sm text-muted-foreground">{distributor.id}</p>
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="space-y-1">
                        <p className="font-medium">{distributor.contact}</p>
                        <div className="flex items-center gap-1 text-xs text-muted-foreground">
                          <Phone className="h-3 w-3" />
                          <span>{distributor.phone}</span>
                        </div>
                        <div className="flex items-center gap-1 text-xs text-muted-foreground">
                          <Mail className="h-3 w-3" />
                          <span>{distributor.email}</span>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-1">
                        <Building2 className="h-3 w-3 text-muted-foreground" />
                        <span>{distributor.tenant}</span>
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="flex items-center gap-1">
                        <MapPin className="h-3 w-3 text-muted-foreground" />
                        <span>{distributor.location}</span>
                      </div>
                    </TableCell>
                    <TableCell>
                      <div className="flex flex-wrap gap-1">
                        {distributor.brands.map((brand) => (
                          <Badge key={brand} variant="outline" className="text-xs">
                            {brand}
                          </Badge>
                        ))}
                      </div>
                    </TableCell>
                    <TableCell>{distributor.retailers}</TableCell>
                    <TableCell>{distributor.monthlyVolume.toLocaleString()}</TableCell>
                    <TableCell>
                      <Badge variant={getPerformanceColor(distributor.performance)}>
                        {distributor.performance}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <Badge variant={getStatusColor(distributor.status)}>
                        {distributor.status}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-1">
                        <Button variant="outline" size="sm">
                          <Edit className="h-3 w-3" />
                        </Button>
                        <Button variant="outline" size="sm">
                          <Trash2 className="h-3 w-3" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
