// src/app/pages/warehouse/alerts/alerts.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { PageHeaderComponent } from '../../../components/ui/page-header/page-header.component';
import { MetricCardComponent } from '../../../components/ui/metric-card/metric-card.component';

@Component({
  selector: 'app-alerts',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatIconModule,
    MatChipsModule,
    PageHeaderComponent,
    MetricCardComponent
  ],
  template: `
    <div class="space-y-8">
      <app-page-header
        title="Warehouse Alerts"
        description="Monitor and manage warehouse alerts, shelf life notifications, and quality checks">
        <button mat-raised-button color="primary">
          <mat-icon>notifications</mat-icon>
          Mark All Read
        </button>
      </app-page-header>

      <!-- Alert Summary Cards -->
      <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <app-metric-card
          *ngFor="let metric of alertSummary"
          [title]="metric.label"
          [value]="metric.value"
          [icon]="metric.icon">
        </app-metric-card>
      </div>

      <!-- Filters -->
      <mat-card>
        <mat-card-header>
          <mat-card-title>Alert Management</mat-card-title>
          <mat-card-subtitle>Filter and manage warehouse alerts by priority and status</mat-card-subtitle>
        </mat-card-header>
        <mat-card-content class="space-y-4">
          <div class="flex flex-col md:flex-row gap-4">
            <mat-form-field appearance="outline" class="flex-1">
              <mat-label>Search</mat-label>
              <input matInput 
                     [(ngModel)]="searchTerm"
                     placeholder="Search alerts by product code, batch, or message...">
              <mat-icon matPrefix>search</mat-icon>
            </mat-form-field>
            
            <mat-form-field appearance="outline" class="w-48">
              <mat-label>Priority</mat-label>
              <mat-select [(ngModel)]="priorityFilter">
                <mat-option value="all">All Priorities</mat-option>
                <mat-option value="critical">Critical</mat-option>
                <mat-option value="high">High</mat-option>
                <mat-option value="medium">Medium</mat-option>
                <mat-option value="low">Low</mat-option>
              </mat-select>
            </mat-form-field>
            
            <mat-form-field appearance="outline" class="w-48">
              <mat-label>Status</mat-label>
              <mat-select [(ngModel)]="statusFilter">
                <mat-option value="all">All Status</mat-option>
                <mat-option value="active">Active</mat-option>
                <mat-option value="pending">Pending</mat-option>
                <mat-option value="resolved">Resolved</mat-option>
              </mat-select>
            </mat-form-field>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Alerts List -->
      <div class="space-y-4">
        <mat-card *ngFor="let alert of filteredAlerts" class="hover:shadow-md transition-shadow">
          <mat-card-content class="p-6">
            <div class="flex items-start justify-between">
              <div class="space-y-3 flex-1">
                <div class="flex items-center gap-3">
                  <mat-chip [color]="getPriorityColor(alert.priority)">{{ alert.priority }}</mat-chip>
                  <mat-chip [color]="getStatusChipColor(alert.status)">{{ alert.status }}</mat-chip>
                  <span class="text-sm text-muted">Alert ID: {{ alert.id }}</span>
                </div>
                
                <div>
                  <h3 class="text-lg font-semibold">{{ alert.type }} Alert</h3>
                  <p class="text-muted">{{ alert.message }}</p>
                </div>
                
                <div class="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                  <div><span class="font-medium">Product:</span><br>{{ alert.productCode }}</div>
                  <div><span class="font-medium">Batch:</span><br>{{ alert.batchNumber }}</div>
                  <div><span class="font-medium">Quantity:</span><br>{{ alert.quantity }} units</div>
                  <div><span class="font-medium">Location:</span><br>{{ alert.location }}</div>
                </div>
                
                <div class="flex items-center gap-4 text-sm text-muted">
                  <span>Created: {{ alert.createdAt | date }}</span>
                  <span>Due: {{ alert.dueDate | date }}</span>
                </div>
              </div>
              
              <div class="flex flex-col gap-2 ml-4">
                <button *ngIf="alert.status === 'Active'" mat-raised-button color="primary">
                  <mat-icon>check_circle</mat-icon>
                  Resolve
                </button>
                <button *ngIf="alert.status === 'Pending'" mat-raised-button color="accent">
                  Take Action
                </button>
                <button mat-stroked-button>View Details</button>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
      </div>

      <mat-card *ngIf="filteredAlerts.length === 0">
        <mat-card-content class="flex flex-col items-center justify-center py-12">
          <mat-icon class="text-6xl text-muted mb-4">warning</mat-icon>
          <h3 class="text-lg font-semibold mb-2">No alerts found</h3>
          <p class="text-muted text-center">
            No alerts match your current filter criteria. Try adjusting your search or filters.
          </p>
        </mat-card-content>
      </mat-card>
    </div>
  `
})
export class AlertsComponent {
  searchTerm = '';
  priorityFilter = 'all';
  statusFilter = 'all';

  alertSummary = [
    { label: 'Critical Alerts', value: '3', icon: 'warning' },
    { label: 'High Priority', value: '8', icon: 'schedule' },
    { label: 'Medium Priority', value: '12', icon: 'inventory' },
    { label: 'Resolved Today', value: '5', icon: 'check_circle' }
  ];

  alerts = [
    {
      id: 'ALT-001',
      type: 'Shelf Life',
      priority: 'High',
      status: 'Active',
      productCode: 'VLT-12V-100AH',
      batchNumber: 'BT2024001',
      message: 'Products nearing expiry date (7 days remaining)',
      quantity: 45,
      location: 'Warehouse A - Zone 3',
      createdAt: '2024-01-15T10:30:00Z',
      dueDate: '2024-01-22T00:00:00Z'
    },
    {
      id: 'ALT-002',
      type: 'Low Stock',
      priority: 'Medium',
      status: 'Active',
      productCode: 'OSK-12V-75AH',
      batchNumber: 'BT2024015',
      message: 'Stock level below minimum threshold (20 units)',
      quantity: 15,
      location: 'Warehouse B - Zone 1',
      createdAt: '2024-01-14T15:45:00Z',
      dueDate: '2024-01-20T00:00:00Z'
    }
  ];

  get filteredAlerts() {
    return this.alerts.filter(alert => {
      const matchesSearch = alert.productCode.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
                           alert.batchNumber.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
                           alert.message.toLowerCase().includes(this.searchTerm.toLowerCase());
      const matchesPriority = this.priorityFilter === 'all' || alert.priority.toLowerCase() === this.priorityFilter;
      const matchesStatus = this.statusFilter === 'all' || alert.status.toLowerCase() === this.statusFilter;
      
      return matchesSearch && matchesPriority && matchesStatus;
    });
  }

  getPriorityColor(priority: string): string {
    switch (priority.toLowerCase()) {
      case 'critical': return 'warn';
      case 'high': return 'warn';
      case 'medium': return 'primary';
      case 'low': return 'accent';
      default: return 'primary';
    }
  }

  getStatusChipColor(status: string): string {
    switch (status.toLowerCase()) {
      case 'active': return 'warn';
      case 'resolved': return 'primary';
      case 'pending': return 'accent';
      default: return 'primary';
    }
  }
}

// src/pages/warehouse/Alerts.tsx
import React, { useState } from 'react';
import { PageHeader } from '@/components/ui/page-header';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { StatusBadge } from '@/components/ui/status-badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { AlertTriangle, Clock, Package, Search, Filter, Bell, CheckCircle, XCircle } from 'lucide-react';

export const Alerts: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [priorityFilter, setPriorityFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');

  const alerts = [
    {
      id: 'ALT-001',
      type: 'Shelf Life',
      priority: 'High',
      status: 'Active',
      productCode: 'VLT-12V-100AH',
      batchNumber: 'BT2024001',
      message: 'Products nearing expiry date (7 days remaining)',
      quantity: 45,
      location: 'Warehouse A - Zone 3',
      createdAt: '2024-01-15T10:30:00Z',
      dueDate: '2024-01-22T00:00:00Z',
    },
    {
      id: 'ALT-002',
      type: 'Low Stock',
      priority: 'Medium',
      status: 'Active',
      productCode: 'OSK-12V-75AH',
      batchNumber: 'BT2024015',
      message: 'Stock level below minimum threshold (20 units)',
      quantity: 15,
      location: 'Warehouse B - Zone 1',
      createdAt: '2024-01-14T15:45:00Z',
      dueDate: '2024-01-20T00:00:00Z',
    },
    {
      id: 'ALT-003',
      type: 'Temperature',
      priority: 'High',
      status: 'Resolved',
      productCode: 'FJK-12V-150AH',
      batchNumber: 'BT2024008',
      message: 'Storage temperature exceeded safe limits',
      quantity: 120,
      location: 'Warehouse C - Zone 2',
      createdAt: '2024-01-13T08:20:00Z',
      dueDate: '2024-01-16T00:00:00Z',
    },
    {
      id: 'ALT-004',
      type: 'Quality Check',
      priority: 'Low',
      status: 'Pending',
      productCode: 'SGA-6V-200AH',
      batchNumber: 'BT2024022',
      message: 'Scheduled quality inspection due',
      quantity: 80,
      location: 'Warehouse A - Zone 1',
      createdAt: '2024-01-12T14:10:00Z',
      dueDate: '2024-01-19T00:00:00Z',
    },
    {
      id: 'ALT-005',
      type: 'Shelf Life',
      priority: 'Critical',
      status: 'Active',
      productCode: 'VLT-12V-65AH',
      batchNumber: 'BT2024003',
      message: 'Products expired - require immediate attention',
      quantity: 28,
      location: 'Warehouse B - Zone 3',
      createdAt: '2024-01-11T09:30:00Z',
      dueDate: '2024-01-11T00:00:00Z',
    },
  ];

  const alertSummary = [
    { label: 'Critical Alerts', value: '3', icon: AlertTriangle, variant: 'destructive' as const },
    { label: 'High Priority', value: '8', icon: Clock, variant: 'warning' as const },
    { label: 'Medium Priority', value: '12', icon: Package, variant: 'default' as const },
    { label: 'Resolved Today', value: '5', icon: CheckCircle, variant: 'success' as const },
  ];

  const getPriorityColor = (priority: string) => {
    switch (priority.toLowerCase()) {
      case 'critical': return 'destructive';
      case 'high': return 'warning';
      case 'medium': return 'default';
      case 'low': return 'secondary';
      default: return 'default';
    }
  };

  const getStatusVariant = (status: string) => {
    switch (status.toLowerCase()) {
      case 'active': return 'warning';
      case 'resolved': return 'success';
      case 'pending': return 'info';
      default: return undefined;
    }
  };

  const filteredAlerts = alerts.filter(alert => {
    const matchesSearch = alert.productCode.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         alert.batchNumber.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         alert.message.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesPriority = priorityFilter === 'all' || alert.priority.toLowerCase() === priorityFilter;
    const matchesStatus = statusFilter === 'all' || alert.status.toLowerCase() === statusFilter;
    
    return matchesSearch && matchesPriority && matchesStatus;
  });

  return (
    <div className="space-y-8">
      <PageHeader
        title="Warehouse Alerts"
        description="Monitor and manage warehouse alerts, shelf life notifications, and quality checks"
        action={
          <Button className="gap-2">
            <Bell className="h-4 w-4" />
            Mark All Read
          </Button>
        }
      />

      {/* Alert Summary Cards */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {alertSummary.map((metric) => (
          <Card key={metric.label}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                {metric.label}
              </CardTitle>
              <metric.icon className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{metric.value}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Alert Management</CardTitle>
          <CardDescription>
            Filter and manage warehouse alerts by priority and status
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex-1">
              <div className="relative">
                <Search className="absolute left-2 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search alerts by product code, batch, or message..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-8"
                />
              </div>
            </div>
            <Select value={priorityFilter} onValueChange={setPriorityFilter}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Filter by priority" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Priorities</SelectItem>
                <SelectItem value="critical">Critical</SelectItem>
                <SelectItem value="high">High</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="low">Low</SelectItem>
              </SelectContent>
            </Select>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Filter by status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                <SelectItem value="active">Active</SelectItem>
                <SelectItem value="pending">Pending</SelectItem>
                <SelectItem value="resolved">Resolved</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Alerts List */}
      <div className="space-y-4">
        {filteredAlerts.map((alert) => (
          <Card key={alert.id} className="hover:shadow-md transition-shadow">
            <CardContent className="p-6">
              <div className="flex items-start justify-between">
                <div className="space-y-3 flex-1">
                  <div className="flex items-center gap-3">
                    <Badge variant={getPriorityColor(alert.priority) as any}>
                      {alert.priority}
                    </Badge>
                    <StatusBadge 
                      status={alert.status} 
                      variant={getStatusVariant(alert.status)}
                    />
                    <span className="text-sm text-muted-foreground">
                      Alert ID: {alert.id}
                    </span>
                  </div>
                  
                  <div>
                    <h3 className="font-semibold text-lg">{alert.type} Alert</h3>
                    <p className="text-muted-foreground">{alert.message}</p>
                  </div>
                  
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                    <div>
                      <span className="font-medium">Product:</span>
                      <br />
                      {alert.productCode}
                    </div>
                    <div>
                      <span className="font-medium">Batch:</span>
                      <br />
                      {alert.batchNumber}
                    </div>
                    <div>
                      <span className="font-medium">Quantity:</span>
                      <br />
                      {alert.quantity} units
                    </div>
                    <div>
                      <span className="font-medium">Location:</span>
                      <br />
                      {alert.location}
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-4 text-sm text-muted-foreground">
                    <span>
                      Created: {new Date(alert.createdAt).toLocaleDateString()}
                    </span>
                    <span>
                      Due: {new Date(alert.dueDate).toLocaleDateString()}
                    </span>
                  </div>
                </div>
                
                <div className="flex flex-col gap-2 ml-4">
                  {alert.status === 'Active' && (
                    <>
                      <Button size="sm" variant="default">
                        <CheckCircle className="h-4 w-4 mr-2" />
                        Resolve
                      </Button>
                      <Button size="sm" variant="outline">
                        View Details
                      </Button>
                    </>
                  )}
                  {alert.status === 'Pending' && (
                    <>
                      <Button size="sm" variant="trustBlue">
                        Take Action
                      </Button>
                      <Button size="sm" variant="outline">
                        View Details
                      </Button>
                    </>
                  )}
                  {alert.status === 'Resolved' && (
                    <Button size="sm" variant="outline">
                      View Details
                    </Button>
                  )}
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {filteredAlerts.length === 0 && (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <AlertTriangle className="h-12 w-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">No alerts found</h3>
            <p className="text-muted-foreground text-center">
              No alerts match your current filter criteria. Try adjusting your search or filters.
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
};
